[Scintilla]
HTML\style0\color=D4D4D4
HTML\style0\eolfill=false
HTML\style0\font=Courier New, 11, 0, 0, 0
HTML\style0\paper=1E1E1E
HTML\style18\color=6A9955
HTML\style18\eolfill=false
HTML\style18\font=Courier New, 11, 0, 0, 0
HTML\style18\paper=1E1E1E
HTML\style104\color=CE9178
HTML\style104\eolfill=false
HTML\style104\font=Courier New, 11, 0, 0, 0
HTML\style104\paper=1E1E1E
HTML\style118\color=D4D4D4
HTML\style118\eolfill=false
HTML\style118\font=Courier New, 11, 0, 0, 0
HTML\style118\paper=1E1E1E
HTML\style119\color=CE9178
HTML\style119\eolfill=false
HTML\style119\font=Courier New, 11, 0, 0, 0
HTML\style119\paper=1E1E1E
HTML\style120\color=CE9178
HTML\style120\eolfill=false
HTML\style120\font=Courier New, 11, 0, 0, 0
HTML\style120\paper=1E1E1E
HTML\style121\color=4EC9B0
HTML\style121\eolfill=false
HTML\style121\font=Courier New, 11, 0, 0, 0
HTML\style121\paper=1E1E1E
HTML\style122\color=C586C0
HTML\style122\eolfill=false
HTML\style122\font=Courier New, 11, 0, 0, 0
HTML\style122\paper=1E1E1E
HTML\style123\color=B5CEA8
HTML\style123\eolfill=false
HTML\style123\font=Courier New, 11, 0, 0, 0
HTML\style123\paper=1E1E1E
HTML\style124\color=6A9955
HTML\style124\eolfill=false
HTML\style124\font=Courier New, 11, 0, 0, 0
HTML\style124\paper=1E1E1E
HTML\style125\color=6A9955
HTML\style125\eolfill=false
HTML\style125\font=Courier New, 11, 0, 0, 0
HTML\style125\paper=1E1E1E
HTML\style126\color=CE9178
HTML\style126\eolfill=false
HTML\style126\font=Courier New, 11, 0, 0, 0
HTML\style126\paper=1E1E1E
HTML\style127\color=858585
HTML\style127\eolfill=false
HTML\style127\font=Courier New, 11, 0, 0, 0
HTML\style127\paper=1E1E1E
HTML\defaultcolor=D4D4D4
HTML\defaultpaper=1E1E1E
HTML\defaultfont=Courier New, 11, 0, 0, 0
HTML\autoindentstyle=-1
