[Scintilla]
HTML\style0\color=ABB2BF
HTML\style0\eolfill=false
HTML\style0\font=Courier New, 12, 0, 0, 0
HTML\style0\paper=282C34
HTML\style18\color=ABB2BF
HTML\style18\eolfill=false
HTML\style18\font=Courier New, 12, 0, 0, 0
HTML\style18\paper=282C34
HTML\style118\color=ABB2BF
HTML\style118\eolfill=false
HTML\style118\font=Courier New, 12, 0, 0, 0
HTML\style118\paper=282C34
HTML\style119\color=98C379
HTML\style119\eolfill=false
HTML\style119\font=Courier New, 12, 0, 0, 0
HTML\style119\paper=282C34
HTML\style120\color=98C379
HTML\style120\eolfill=false
HTML\style120\font=Courier New, 12, 0, 0, 0
HTML\style120\paper=282C34
HTML\style121\color=D19A66
HTML\style121\eolfill=false
HTML\style121\font=Courier New, 12, 0, 0, 0
HTML\style121\paper=282C34
HTML\style122\color=E06C75
HTML\style122\eolfill=false
HTML\style122\font=Courier New, 12, 0, 0, 0
HTML\style122\paper=282C34
HTML\style123\color=D19A66
HTML\style123\eolfill=false
HTML\style123\font=Courier New, 12, 0, 0, 0
HTML\style123\paper=282C34
HTML\style124\color=98C379
HTML\style124\eolfill=false
HTML\style124\font=Courier New, 12, 0, 0, 0
HTML\style124\paper=282C34
HTML\style125\color=98C379
HTML\style125\eolfill=false
HTML\style125\font=Courier New, 12, 0, 0, 0
HTML\style125\paper=282C34
HTML\style126\color=98C379
HTML\style126\eolfill=false
HTML\style126\font=Courier New, 12, 0, 0, 0
HTML\style126\paper=282C34
HTML\style127\color=D19A66
HTML\style127\eolfill=false
HTML\style127\font=Courier New, 12, 0, 0, 0
HTML\style127\paper=282C34
HTML\defaultcolor=ABB2BF
HTML\defaultpaper=282C34
HTML\defaultfont=Courier New, 12, 0, 0, 0
HTML\autoindentstyle=-1
